export const game = {
	value: null,
	disable: true,
	health: 3,
	level: 1,
	digits: 3,
	start: false,
	answerArray: [],
	answer: true,
	sequence: [4, 5, 6],
	answerList: [],
	score: 0,
	success: false,
	answering: false,
};
